# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'T\'s Notebook' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'Hero'
  # Pods for T's Notebook

  target 'T\'s NotebookTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'T\'s NotebookUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
